GO
GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA :: [Stg_Rpt] TO [Role_Service_Account];
GO
GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA :: [ODS_Rpt] TO [Role_Service_Account];
GO
GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA :: [log] TO [Role_Service_Account];


--ALTER ROLE [Role_Service_Account] ADD MEMBER [BCIMC\RISK_ETL_DEV_SRV];
