GO
GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA :: [Stg_Rpt] TO [Stg_Rpt];
GO
GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA :: [ODS_Rpt] TO [ODS_Rpt];
GO
GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA :: [log] TO [log];