#loading packages
if (!require('dplyr')) install.packages('dplyr')
if (!require('ggplot2')) install.packages('ggplot2')
if (!require('ggrepel')) install.packages('ggrepel')
if (!require('ggthemes')) install.packages('ggthemes')
if (!require('grid')) install.packages('grid')
if (!require('plotly')) install.packages('plotly')
if (!require('raster')) install.packages('raster')
if (!require('RColorBrewer')) install.packages('RColorBrewer')
if (!require('reshape')) install.packages('reshape')
if (!require('scales')) install.packages('scales')

library(dplyr)
library(ggplot2)
library(ggrepel)
library(ggthemes)
library(grid)
library(plotly)
library(raster)
library(RColorBrewer)
library(reshape)
library(scales)
