GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA :: [Rpt] TO [Role_Service_Account];
GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA :: [Stg_Rpt] TO [Role_Service_Account];


--ALTER ROLE [Role_ServiceAccount] ADD MEMBER [BCIMC\RISK_ETL_DEV_SRV];
