CREATE TABLE [Stg_Rpt].[FI_Exposures_by_Rating] (
    [FI_Exposures_by_Rating_Key]     INT            IDENTITY (1, 1) NOT NULL,
    [QY_Date]                        NVARCHAR (50)  NULL,
    [Rating]                         NVARCHAR (50)  NULL,
    [Type]                           NVARCHAR (50)  NULL,
    [MV_$M]                          NVARCHAR (50)  NULL,
    [Active_Weight]                  NVARCHAR (50)  NULL,
    [DV01_Curr]                      NVARCHAR (50)  NULL,
    [DV01_Prev]                      NVARCHAR (50)  NULL,
    [Pf_Effective_Duration_Curr]     NVARCHAR (50)  NULL,
    [Pf_Effective_Duration_Prev]     NVARCHAR (50)  NULL,
    [Active_Eff_Duration_Curr]       NVARCHAR (50)  NULL,
    [Active_Eff_Duration_Prev]       NVARCHAR (50)  NULL,
    [PF_Duration_Contribution_Curr]  NVARCHAR (50)  NULL,
    [PF_Duration_Contribution_Prev]  NVARCHAR (50)  NULL,
    [BMK_Effective_Duration_Curr]    NVARCHAR (50)  NULL,
    [BMK_Effective_Duration_Prev]    NVARCHAR (50)  NULL,
    [PF_New_Weight_Curr]             NVARCHAR (50)  NULL,
    [PF_New_Weight_Prev]             NVARCHAR (50)  NULL,
    [BMK_Duration_Contribution_Curr] NVARCHAR (50)  NULL,
    [BMK_New_Weights_Curr]           NVARCHAR (50)  NULL,
    [BMK_Weight_Curr]                NVARCHAR (50)  NULL,
    [BMK_Duration_Contribution_Prev] NVARCHAR (50)  NULL,
    [BMK_New_Weights_Prev]           NVARCHAR (50)  NULL,
    [BMK_Weight_Prev]                NVARCHAR (50)  NULL,
    [Source]                         NVARCHAR (150) NULL,
    [ETL_Load_Date]                  DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([FI_Exposures_by_Rating_Key] ASC) 
);

